name: dartup_conf
description: A web server built using the shelf package.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.1.0

  # FOR SERVING STATIC FILES
  shelf_static: ^1.1.0

  # DEFINE THE ROUTES
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
